Letterboxd support (fix #30)
trossr32/sonarr-radarr-lidarr-autosearch-browser-extension pull request #31
Opened 2021-01-03 12:18 UTC by aommm

Add integration towards Letterboxd
(WIP)

2021-01-03 21:05 UTC, trossr32 requested changes
Hi,

Thanks for doing this work, it's really appreciated!

I've tested the code and there's a change I'd like to make. When testing against https://letterboxd.com/film/wonder-woman-1984/ Radarr can't find a moview using the search string 'wonder woman 1984'. It does however work for the terms 'ww84' or 'wonder woman 1984 (2020)'. The easiest way to fix this is to the use the following config for letterboxd in the content_script.js file, which takes the search term from the <meta property="og:title" content="Wonder Woman 1984 (2020)"> tag in the markup's head tag:

```
{
    id: 'letterboxd',
    defaultSite: 'radarr',
    search: {
        containerSelector: 'meta[property="og:title"]',
        selectorType: 'content',
        modifier: null
    },
    match: {
        term: 'letterboxd.com/film/'
    },
    icon: {
        containerSelector: '#featured-film-header > h1',
        locator: 'prepend',
        imgStyles: 'width: 25px; margin: 8px 10px 0 0; float: left;'
    }
}
```

This also removes the need to regex replace newlines in the search term, although I'm happy for that to be left in as it certainly doesn't hurt to have it there.

Additionally, the following switch:

```
switch (integration.search.selectorType) {
    case 'href':
        searchTerm = $(container).attr('href');
        break;

    default: // text
        searchTerm = $(container).text();
        break;
}
```

needs to be replaced with:

```
switch (integration.search.selectorType) {
    case 'href':
        searchTerm = $(container).attr('href');
        break;

    case 'content':
        searchTerm = $(container).attr('content');
        break;

    default: // text
        searchTerm = $(container).text();
        break;
}
```

I'm happy to make the change if you grant me access to your forked repo (https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork), or you can do it and update the pull request.

Again, really appreciate the effort you've put in 👍

2021-01-03 21:07 UTC, trossr32 commented on ChromiumExtension/content/js/content_script.js
> +        },
```
{
    id: 'letterboxd',
    defaultSite: 'radarr',
    search: {
        containerSelector: 'meta[property="og:title"]',
        selectorType: 'content',
        modifier: null
    },
    match: {
        term: 'letterboxd.com/film/'
    },
    icon: {
        containerSelector: '#featured-film-header > h1',
        locator: 'prepend',
        imgStyles: 'width: 25px; margin: 8px 10px 0 0; float: left;'
    }
}

2021-01-03 21:07 UTC, trossr32 commented on FirefoxAddOn/content/js/content_script.js
> +        },
```
{
    id: 'letterboxd',
    defaultSite: 'radarr',
    search: {
        containerSelector: 'meta[property="og:title"]',
        selectorType: 'content',
        modifier: null
    },
    match: {
        term: 'letterboxd.com/film/'
    },
    icon: {
        containerSelector: '#featured-film-header > h1',
        locator: 'prepend',
        imgStyles: 'width: 25px; margin: 8px 10px 0 0; float: left;'
    }
}

2021-01-05 17:38 UTC, aommm commented
Thanks for the feedback, I have made the necessary updates!

Just want to point out that my original solution did work for e.g. [Wonder Woman 1984](https://letterboxd.com/film/wonder-woman-1984/); it would have extracted "Wonder Woman 1984 2020".

But I like your proposed solution more, it is definitely less brittle. (I didn't notice those meta tags myself 🤦)

I left the "strip spaces" code in because it might still be useful down the road.

So this is ready for review again.

2021-01-05 18:43 UTC, trossr32 approved these changes
Excellent, thank you! Approved.

2021-01-05 18:44 UTC, merged